PANDAS:
Pandas is an open-source Python library designed for data manipulation and analysis. 
Two main types - DataFrame, Series (row/column)
DataFrame - A 2D labeled data structure (like a full spreadsheet or SQL table)
Series - A 1D labeled array (like a column)

In [1]:
import pandas as pd

DataFrame:
df = pd.read_csv('data.csv')        # Load from CSV
df = pd.read_excel('data.xlsx')     # Load from Excel
df = pd.DataFrame(data_dict)        # Load from dictionary

df.head()        # First 5 rows
df.tail()        # Last 5 rows
df.info()        # Column types and non-null values
df.describe()    # Summary stats
df.columns       # Column names
df.index         # Row indices

df['Age']                  # Single column
df[['Name', 'Age']]        # Multiple columns
df.iloc[0]                 # First row by position
df.loc[0]                  # First row by label

df[df['Age'] > 30]                          # Age over 30
df[(df['Age'] > 25) & (df['Country'] == 'UK')]  # Multiple conditions

df[df['Name'].str.startswith('A')]         # Names starting with A
df[df['Country'].isin(['USA', 'UK'])]      # Match multiple values
df[~df['Country'].isin(['Canada'])]        # NOT condition

In [3]:
df = pd.read_csv('carprices.csv')
df.head()

  Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [6]:
df[['Car Model', 'Mileage']].head()

  Car Model  Mileage
0    BMW X5    69000
1    BMW X5    35000
2    BMW X5    57000
3    BMW X5    22500
4    BMW X5    46000

In [ ]:
df.iloc[0] #values for first row

Car Model        BMW X5
Mileage           69000
Sell Price($)     18000
Age(yrs)              6
Name: 0, dtype: object